# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [3]:
##Se crea un Array con la función .array() de Numpy
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)


[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
##Se crea un Array lleno de 0 con la función .zeros() de Numpy y le pasamos las dimensiones como paramétro.
arr = np.zeros(5)
print(f"Array inicializado: {arr}")
##Accedemos al 3er elemento a través del índice y modificamos su valor.
arr[2] = 5
print(f"Array después de la modificación: {arr}")

Array inicializado:[0. 0. 0. 0. 0.]
Array después de la modificación:[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [21]:
##Creamos una Array con la función randint() que toma como parametros el menor número, el mayor número y las dimensiones del Array
arr = np.random.randint(0,2,[3,3])
print(arr)

[[1 0 0]
 [1 1 1]
 [1 0 0]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [4]:
arr = np.array([10,20,30,40,50])
##Creamos un número aleatorio con la función randint() del módulo random
numeroAleatorio = randint(1,10)

##Imprimimos la suma
print(f"La suma de cada elemento del array {arr} por 5 es:")
print(arr + 5)
print(f"La suma de cada elemento del array {arr} por un número aleatorio ({numeroAleatorio}) es:")
print(arr + numeroAleatorio)



La suma de cada elemento del array [10 20 30 40 50] por 5 es:
[15 25 35 45 55]
La suma de cada elemento del array [10 20 30 40 50] por un número aleatorio (6) es:
[16 26 36 46 56]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#Se crea una matriz identidad con la función .identity() de numpy especificando la cantidad de números de la diágonal principal.
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 

